version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7
    container_name: opendesign-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: opendesign
    volumes:
      - mongodb_data:/data/db
    networks:
      - opendesign-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: opendesign-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - opendesign-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: opendesign-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/opendesign?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      FRONTEND_URL: http://localhost:3000
      PORT: 5000
    depends_on:
      - mongodb
      - redis
    networks:
      - opendesign-network
    volumes:
      - ./backend/logs:/app/logs

  # Frontend (Next.js)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opendesign-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
      NEXT_PUBLIC_WS_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - opendesign-network

volumes:
  mongodb_data:
  redis_data:

networks:
  opendesign-network:
    driver: bridge